name: Deploy JSP Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save Private Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add EC2 Host to Known Hosts
        run: |
          if [ -z "${{ secrets.HOST }}" ]; then
            echo "Error: HOST is not defined" && exit 1
          fi
          echo "Adding ${{ secrets.HOST }} to known hosts..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          echo "Host added successfully."

      - name: Debug SSH Connection
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST echo "SSH connection successful"

      - name: Set Permissions for mvnw
        run: chmod +x ./mvnw

      - name: Build Project
        run: ./mvnw clean package -DskipTests

      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem ./target/*.war $USER@$HOST:/opt/tomcat10/webapps/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            sudo systemctl restart tomcat
          EOF
