name: Deploy JSP Frontend to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 2: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Save EC2 private key to file
      - name: Save Private Key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Step 4: Add EC2 host to known hosts
      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Step 5: Set execute permissions for Maven Wrapper
      - name: Set Permissions for mvnw
        run: chmod +x ./mvnw

      # Step 6: Build the JSP application
      - name: Build Project
        run: ./mvnw clean package -DskipTests

      # Step 7: Deploy JSP files to Tomcat
      # Debug SSH Connection
      - name: Debug SSH Connection
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: ssh -i private_key.pem $USER@$HOST echo "SSH connection successful"


      # Step 8: Delete all existing WAR files in Tomcat webapps directory
      - name: Delete Existing WAR Files
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            echo "Deleting all existing WAR files in the webapps directory"
            sudo rm -rf /opt/tomcat10/webapps/*.war
          EOF

      # Step 9: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Copy the WAR file to a temporary directory (where the user has write access)
          scp -o StrictHostKeyChecking=no -i private_key.pem ./target/EventsFlow.war $USER@$HOST:/home/$USER/

          # SSH into the EC2 instance and move the WAR file to Tomcat's webapps directory
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            # Move the WAR file to the Tomcat webapps directory
            sudo mv /home/$USER/EventsFlow.war /opt/tomcat/webapps/

            # Change the ownership to tomcat user (if necessary)
            sudo chown tomcat:tomcat /opt/tomcat/webapps/EventsFlow.war

            # Restart Tomcat to load the new deployment
            sudo systemctl restart tomcat
          EOF
